package example_cdr;

/*
 * Created by JAC (Java Asn1 Compiler)
 */

import com.turkcelltech.jac.*;
import com.chaosinmotion.asn1.Tag;

public class CallDetailRecord extends Sequence
{
	/**
	 * if you want to set/fill an element below, just call the setValue(..) method over its instance.
	 *
	 * To encode/decode your object, just call encode(..) decode(..) methods.
	 */
	public AddressInformation origAddress = new AddressInformation("origAddress");
	public AddressString origAddressGSM = new AddressString("origAddressGSM");
	public AddressInformation recipAddress = new AddressInformation("recipAddress");
	public AddressString recipAddressGSM = new AddressString("recipAddressGSM");
	public Date submitDate = new Date("submitDate");
	public Time submitTime = new Time("submitTime");
	public Status status = new Status("status");
	public Date terminDate = new Date("terminDate");
	public Time terminTime = new Time("terminTime");
	public MessageLength lengthOfMessage = new MessageLength("lengthOfMessage");
	public ASN1Boolean prioIndicator = new ASN1Boolean("prioIndicator");
	public Period validityPeriod = new Period("validityPeriod");
	public ASN1Boolean deferIndicator = new ASN1Boolean("deferIndicator");
	public Period deferPeriod = new Period("deferPeriod");
	public ASN1Boolean notifIndicator = new ASN1Boolean("notifIndicator");
	public AddressInformation notifAddress = new AddressInformation("notifAddress");
	public AddressString notifAddressGSM = new AddressString("notifAddressGSM");
	public RangeVSMSC vsmscid = new RangeVSMSC("vsmscid");
	public TypeVSMSC vsmsctype = new TypeVSMSC("vsmsctype");
	public AddressInformation dgtiAddress = new AddressInformation("dgtiAddress");
	public AddressString dgtiAddressGSM = new AddressString("dgtiAddressGSM");
	public C7PointCode destPointCode = new C7PointCode("destPointCode");
	public AddressInformation ogtiAddress = new AddressInformation("ogtiAddress");
	public AddressString ogtiAddressGSM = new AddressString("ogtiAddressGSM");
	public C7PointCode origPointCode = new C7PointCode("origPointCode");
	public Date orglSubmitDate = new Date("orglSubmitDate");
	public Time orglSubmitTime = new Time("orglSubmitTime");
	public TransparentPid transparentPid = new TransparentPid("transparentPid");
	public MesgReplyPath mesgReplyPath = new MesgReplyPath("mesgReplyPath");
	public IMSI intlMobileSubId = new IMSI("intlMobileSubId");
	public AddressInformation callingLineId = new AddressInformation("callingLineId");
	public AddressString callingLineIdGSM = new AddressString("callingLineIdGSM");
	public IA5String consolidation = new IA5String("consolidation");
	public PortNumber portNumber = new PortNumber("portNumber");
	public AdditionalServices aser = new AdditionalServices("aser");
	public RequestedServices mser = new RequestedServices("mser");
	public NewServices nser = new NewServices("nser");
	public ExtraServices xser = new ExtraServices("xser");
	public IMSI origIntlMobileSubId = new IMSI("origIntlMobileSubId");
	public IA5String billid = new IA5String("billid");
	public LanguageIndicator lang = new LanguageIndicator("lang");
	public IA5String cbat = new IA5String("cbat");
	public PrepaidPrimSer ppPser = new PrepaidPrimSer("ppPser");
	public PrepaidAddSer ppAser = new PrepaidAddSer("ppAser");
	public PrepaidAddSer ppAserDuringJam = new PrepaidAddSer("ppAserDuringJam");
	public PrepaidAddSer ppAserFree = new PrepaidAddSer("ppAserFree");
	public PrepaidAddSer ppAserRecip = new PrepaidAddSer("ppAserRecip");
	public SmeReference smeReference = new SmeReference("smeReference");
	public IA5String smsContentDcs = new IA5String("smsContentDcs");
	public SMSSTRING smsContents = new SMSSTRING("smsContents");
	public CmReference cmReferenceNr = new CmReference("cmReferenceNr");
	public CmNumber currentSegment = new CmNumber("currentSegment");
	public CmNumber segmentsTotal = new CmNumber("segmentsTotal");
	public EmsBitString textFormatting = new EmsBitString("textFormatting");
	public EmsBytesCompressed bytesCompressedData = new EmsBytesCompressed("bytesCompressedData");
	public EmsNumber predefinedAnimations = new EmsNumber("predefinedAnimations");
	public EmsNumber userDefinedAnimations = new EmsNumber("userDefinedAnimations");
	public EmsNumber predefinedSounds = new EmsNumber("predefinedSounds");
	public EmsNumber userDefinedSounds = new EmsNumber("userDefinedSounds");
	public EmsNumber blackWhitePictures = new EmsNumber("blackWhitePictures");
	public EmsNumber standardWvg = new EmsNumber("standardWvg");
	public EmsNumber characterSizeWvg = new EmsNumber("characterSizeWvg");
	public EmsNumber greyscalePictures = new EmsNumber("greyscalePictures");
	public EmsNumber colourPictures = new EmsNumber("colourPictures");
	public EmsNumber businessCards = new EmsNumber("businessCards");
	public EmsNumber calendarEntries = new EmsNumber("calendarEntries");
	public EmsNumber polyphonicMelodies = new EmsNumber("polyphonicMelodies");
	public EmsPortNumbers8 bit8PortNumberDest = new EmsPortNumbers8("bit8PortNumberDest");
	public EmsPortNumbers16 bit16PortNumberDest = new EmsPortNumbers16("bit16PortNumberDest");
	public LmsgNumseg lmsgNrSeg = new LmsgNumseg("lmsgNrSeg");
	public MsgRef messageReference = new MsgRef("messageReference");
	public BooleanServices boolSer = new BooleanServices("boolSer");
	public IA5String origLASN = new IA5String("origLASN");
	public IA5String recipLASN = new IA5String("recipLASN");
	public IA5String origMsgID = new IA5String("origMsgID");
	public IA5String recipMsgID = new IA5String("recipMsgID");
	public Date receiptDate = new Date("receiptDate");
	public Time receiptTime = new Time("receiptTime");
	public ISRFlags isr = new ISRFlags("isr");
	public AddressInformation recipAltAddress = new AddressInformation("recipAltAddress");
	public NumGenSegments generatedSegments = new NumGenSegments("generatedSegments");
	public IA5String serviceType = new IA5String("serviceType");
	public DeliveryAttempts deliveryAttempts = new DeliveryAttempts("deliveryAttempts");
	public UTF8AddressInformation untranslOrigAddress = new UTF8AddressInformation("untranslOrigAddress");
	public AddressString untranslOrigAddressGSM = new AddressString("untranslOrigAddressGSM");
	public UTF8AddressInformation untranslRecipAddress = new UTF8AddressInformation("untranslRecipAddress");
	public AddressString untranslRecipAddressGSM = new AddressString("untranslRecipAddressGSM");
	public MessageError msgError = new MessageError("msgError");
	public GSMTPDCS tpDCS = new GSMTPDCS("tpDCS");
	public OctetString subscriptionType = new OctetString("subscriptionType");
	public OctetString predefinedPaymentOption = new OctetString("predefinedPaymentOption");
	public IA5String iNRatedAmount = new IA5String("iNRatedAmount");
	/* end of element declarations */
	
	/**
	* asn.1 SEQUENCE constructor
	*/
	public
	CallDetailRecord()
	{
		super();
		setUpElements();
	}

	/**
	* asn.1 SEQUENCE constructor with its name
	*/
	public
	CallDetailRecord(String name)
	{
		super(name);
		setUpElements();
	}
	

	protected void
	setUpElements()
	{
		super.addElement(origAddress);
		origAddress.setOptional(true);
		origAddress.setTaggingMethod(Tag.IMPLICIT);
		origAddress.setTagClass(Tag.CONTEXT);
		origAddress.setTagNumber(0);
		super.addElement(origAddressGSM);
		origAddressGSM.setOptional(true);
		origAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		origAddressGSM.setTagClass(Tag.CONTEXT);
		origAddressGSM.setTagNumber(1);
		super.addElement(recipAddress);
		recipAddress.setOptional(true);
		recipAddress.setTaggingMethod(Tag.IMPLICIT);
		recipAddress.setTagClass(Tag.CONTEXT);
		recipAddress.setTagNumber(2);
		super.addElement(recipAddressGSM);
		recipAddressGSM.setOptional(true);
		recipAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		recipAddressGSM.setTagClass(Tag.CONTEXT);
		recipAddressGSM.setTagNumber(3);
		super.addElement(submitDate);
		submitDate.setOptional(true);
		submitDate.setTaggingMethod(Tag.IMPLICIT);
		submitDate.setTagClass(Tag.CONTEXT);
		submitDate.setTagNumber(4);
		super.addElement(submitTime);
		submitTime.setOptional(true);
		submitTime.setTaggingMethod(Tag.IMPLICIT);
		submitTime.setTagClass(Tag.CONTEXT);
		submitTime.setTagNumber(5);
		super.addElement(status);
		status.setOptional(true);
		status.setTaggingMethod(Tag.IMPLICIT);
		status.setTagClass(Tag.CONTEXT);
		status.setTagNumber(6);
		super.addElement(terminDate);
		terminDate.setOptional(true);
		terminDate.setTaggingMethod(Tag.IMPLICIT);
		terminDate.setTagClass(Tag.CONTEXT);
		terminDate.setTagNumber(7);
		super.addElement(terminTime);
		terminTime.setOptional(true);
		terminTime.setTaggingMethod(Tag.IMPLICIT);
		terminTime.setTagClass(Tag.CONTEXT);
		terminTime.setTagNumber(8);
		super.addElement(lengthOfMessage);
		lengthOfMessage.setOptional(true);
		lengthOfMessage.setTaggingMethod(Tag.IMPLICIT);
		lengthOfMessage.setTagClass(Tag.CONTEXT);
		lengthOfMessage.setTagNumber(9);
		super.addElement(prioIndicator);
		prioIndicator.setOptional(true);
		prioIndicator.setTaggingMethod(Tag.IMPLICIT);
		prioIndicator.setTagClass(Tag.CONTEXT);
		prioIndicator.setTagNumber(10);
		super.addElement(validityPeriod);
		validityPeriod.setOptional(true);
		validityPeriod.setTaggingMethod(Tag.IMPLICIT);
		validityPeriod.setTagClass(Tag.CONTEXT);
		validityPeriod.setTagNumber(11);
		super.addElement(deferIndicator);
		deferIndicator.setOptional(true);
		deferIndicator.setTaggingMethod(Tag.IMPLICIT);
		deferIndicator.setTagClass(Tag.CONTEXT);
		deferIndicator.setTagNumber(12);
		super.addElement(deferPeriod);
		deferPeriod.setOptional(true);
		deferPeriod.setTaggingMethod(Tag.IMPLICIT);
		deferPeriod.setTagClass(Tag.CONTEXT);
		deferPeriod.setTagNumber(13);
		super.addElement(notifIndicator);
		notifIndicator.setOptional(true);
		notifIndicator.setTaggingMethod(Tag.IMPLICIT);
		notifIndicator.setTagClass(Tag.CONTEXT);
		notifIndicator.setTagNumber(14);
		super.addElement(notifAddress);
		notifAddress.setOptional(true);
		notifAddress.setTaggingMethod(Tag.IMPLICIT);
		notifAddress.setTagClass(Tag.CONTEXT);
		notifAddress.setTagNumber(15);
		super.addElement(notifAddressGSM);
		notifAddressGSM.setOptional(true);
		notifAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		notifAddressGSM.setTagClass(Tag.CONTEXT);
		notifAddressGSM.setTagNumber(16);
		super.addElement(vsmscid);
		vsmscid.setOptional(true);
		vsmscid.setTaggingMethod(Tag.IMPLICIT);
		vsmscid.setTagClass(Tag.CONTEXT);
		vsmscid.setTagNumber(17);
		super.addElement(vsmsctype);
		vsmsctype.setOptional(true);
		vsmsctype.setTaggingMethod(Tag.IMPLICIT);
		vsmsctype.setTagClass(Tag.CONTEXT);
		vsmsctype.setTagNumber(18);
		super.addElement(dgtiAddress);
		dgtiAddress.setOptional(true);
		dgtiAddress.setTaggingMethod(Tag.IMPLICIT);
		dgtiAddress.setTagClass(Tag.CONTEXT);
		dgtiAddress.setTagNumber(19);
		super.addElement(dgtiAddressGSM);
		dgtiAddressGSM.setOptional(true);
		dgtiAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		dgtiAddressGSM.setTagClass(Tag.CONTEXT);
		dgtiAddressGSM.setTagNumber(20);
		super.addElement(destPointCode);
		destPointCode.setOptional(true);
		destPointCode.setTaggingMethod(Tag.IMPLICIT);
		destPointCode.setTagClass(Tag.CONTEXT);
		destPointCode.setTagNumber(21);
		super.addElement(ogtiAddress);
		ogtiAddress.setOptional(true);
		ogtiAddress.setTaggingMethod(Tag.IMPLICIT);
		ogtiAddress.setTagClass(Tag.CONTEXT);
		ogtiAddress.setTagNumber(22);
		super.addElement(ogtiAddressGSM);
		ogtiAddressGSM.setOptional(true);
		ogtiAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		ogtiAddressGSM.setTagClass(Tag.CONTEXT);
		ogtiAddressGSM.setTagNumber(23);
		super.addElement(origPointCode);
		origPointCode.setOptional(true);
		origPointCode.setTaggingMethod(Tag.IMPLICIT);
		origPointCode.setTagClass(Tag.CONTEXT);
		origPointCode.setTagNumber(24);
		super.addElement(orglSubmitDate);
		orglSubmitDate.setOptional(true);
		orglSubmitDate.setTaggingMethod(Tag.IMPLICIT);
		orglSubmitDate.setTagClass(Tag.CONTEXT);
		orglSubmitDate.setTagNumber(25);
		super.addElement(orglSubmitTime);
		orglSubmitTime.setOptional(true);
		orglSubmitTime.setTaggingMethod(Tag.IMPLICIT);
		orglSubmitTime.setTagClass(Tag.CONTEXT);
		orglSubmitTime.setTagNumber(26);
		super.addElement(transparentPid);
		transparentPid.setOptional(true);
		transparentPid.setTaggingMethod(Tag.IMPLICIT);
		transparentPid.setTagClass(Tag.CONTEXT);
		transparentPid.setTagNumber(27);
		super.addElement(mesgReplyPath);
		mesgReplyPath.setOptional(true);
		mesgReplyPath.setTaggingMethod(Tag.IMPLICIT);
		mesgReplyPath.setTagClass(Tag.CONTEXT);
		mesgReplyPath.setTagNumber(28);
		super.addElement(intlMobileSubId);
		intlMobileSubId.setOptional(true);
		intlMobileSubId.setTaggingMethod(Tag.IMPLICIT);
		intlMobileSubId.setTagClass(Tag.CONTEXT);
		intlMobileSubId.setTagNumber(29);
		super.addElement(callingLineId);
		callingLineId.setOptional(true);
		callingLineId.setTaggingMethod(Tag.IMPLICIT);
		callingLineId.setTagClass(Tag.CONTEXT);
		callingLineId.setTagNumber(30);
		super.addElement(callingLineIdGSM);
		callingLineIdGSM.setOptional(true);
		callingLineIdGSM.setTaggingMethod(Tag.IMPLICIT);
		callingLineIdGSM.setTagClass(Tag.CONTEXT);
		callingLineIdGSM.setTagNumber(31);
		super.addElement(consolidation);
		consolidation.setOptional(true);
		consolidation.setTaggingMethod(Tag.IMPLICIT);
		consolidation.setTagClass(Tag.CONTEXT);
		consolidation.setTagNumber(32);
		super.addElement(portNumber);
		portNumber.setOptional(true);
		portNumber.setTaggingMethod(Tag.IMPLICIT);
		portNumber.setTagClass(Tag.CONTEXT);
		portNumber.setTagNumber(33);
		super.addElement(aser);
		aser.setOptional(true);
		aser.setTaggingMethod(Tag.IMPLICIT);
		aser.setTagClass(Tag.CONTEXT);
		aser.setTagNumber(34);
		super.addElement(mser);
		mser.setOptional(true);
		mser.setTaggingMethod(Tag.IMPLICIT);
		mser.setTagClass(Tag.CONTEXT);
		mser.setTagNumber(35);
		super.addElement(nser);
		nser.setOptional(true);
		nser.setTaggingMethod(Tag.IMPLICIT);
		nser.setTagClass(Tag.CONTEXT);
		nser.setTagNumber(36);
		super.addElement(xser);
		xser.setOptional(true);
		xser.setTaggingMethod(Tag.IMPLICIT);
		xser.setTagClass(Tag.CONTEXT);
		xser.setTagNumber(37);
		super.addElement(origIntlMobileSubId);
		origIntlMobileSubId.setOptional(true);
		origIntlMobileSubId.setTaggingMethod(Tag.IMPLICIT);
		origIntlMobileSubId.setTagClass(Tag.CONTEXT);
		origIntlMobileSubId.setTagNumber(38);
		super.addElement(billid);
		billid.setOptional(true);
		billid.setTaggingMethod(Tag.IMPLICIT);
		billid.setTagClass(Tag.CONTEXT);
		billid.setTagNumber(39);
		super.addElement(lang);
		lang.setOptional(true);
		lang.setTaggingMethod(Tag.IMPLICIT);
		lang.setTagClass(Tag.CONTEXT);
		lang.setTagNumber(40);
		super.addElement(cbat);
		cbat.setOptional(true);
		cbat.setTaggingMethod(Tag.IMPLICIT);
		cbat.setTagClass(Tag.CONTEXT);
		cbat.setTagNumber(41);
		super.addElement(ppPser);
		ppPser.setOptional(true);
		ppPser.setTaggingMethod(Tag.IMPLICIT);
		ppPser.setTagClass(Tag.CONTEXT);
		ppPser.setTagNumber(42);
		super.addElement(ppAser);
		ppAser.setOptional(true);
		ppAser.setTaggingMethod(Tag.IMPLICIT);
		ppAser.setTagClass(Tag.CONTEXT);
		ppAser.setTagNumber(43);
		super.addElement(ppAserDuringJam);
		ppAserDuringJam.setOptional(true);
		ppAserDuringJam.setTaggingMethod(Tag.IMPLICIT);
		ppAserDuringJam.setTagClass(Tag.CONTEXT);
		ppAserDuringJam.setTagNumber(44);
		super.addElement(ppAserFree);
		ppAserFree.setOptional(true);
		ppAserFree.setTaggingMethod(Tag.IMPLICIT);
		ppAserFree.setTagClass(Tag.CONTEXT);
		ppAserFree.setTagNumber(45);
		super.addElement(ppAserRecip);
		ppAserRecip.setOptional(true);
		ppAserRecip.setTaggingMethod(Tag.IMPLICIT);
		ppAserRecip.setTagClass(Tag.CONTEXT);
		ppAserRecip.setTagNumber(46);
		super.addElement(smeReference);
		smeReference.setOptional(true);
		smeReference.setTaggingMethod(Tag.IMPLICIT);
		smeReference.setTagClass(Tag.CONTEXT);
		smeReference.setTagNumber(47);
		super.addElement(smsContentDcs);
		smsContentDcs.setOptional(true);
		smsContentDcs.setTaggingMethod(Tag.IMPLICIT);
		smsContentDcs.setTagClass(Tag.CONTEXT);
		smsContentDcs.setTagNumber(48);
		super.addElement(smsContents);
		smsContents.setOptional(true);
		smsContents.setTaggingMethod(Tag.IMPLICIT);
		smsContents.setTagClass(Tag.CONTEXT);
		smsContents.setTagNumber(49);
		super.addElement(cmReferenceNr);
		cmReferenceNr.setOptional(true);
		cmReferenceNr.setTaggingMethod(Tag.IMPLICIT);
		cmReferenceNr.setTagClass(Tag.CONTEXT);
		cmReferenceNr.setTagNumber(50);
		super.addElement(currentSegment);
		currentSegment.setOptional(true);
		currentSegment.setTaggingMethod(Tag.IMPLICIT);
		currentSegment.setTagClass(Tag.CONTEXT);
		currentSegment.setTagNumber(51);
		super.addElement(segmentsTotal);
		segmentsTotal.setOptional(true);
		segmentsTotal.setTaggingMethod(Tag.IMPLICIT);
		segmentsTotal.setTagClass(Tag.CONTEXT);
		segmentsTotal.setTagNumber(52);
		super.addElement(textFormatting);
		textFormatting.setOptional(true);
		textFormatting.setTaggingMethod(Tag.IMPLICIT);
		textFormatting.setTagClass(Tag.CONTEXT);
		textFormatting.setTagNumber(53);
		super.addElement(bytesCompressedData);
		bytesCompressedData.setOptional(true);
		bytesCompressedData.setTaggingMethod(Tag.IMPLICIT);
		bytesCompressedData.setTagClass(Tag.CONTEXT);
		bytesCompressedData.setTagNumber(54);
		super.addElement(predefinedAnimations);
		predefinedAnimations.setOptional(true);
		predefinedAnimations.setTaggingMethod(Tag.IMPLICIT);
		predefinedAnimations.setTagClass(Tag.CONTEXT);
		predefinedAnimations.setTagNumber(55);
		super.addElement(userDefinedAnimations);
		userDefinedAnimations.setOptional(true);
		userDefinedAnimations.setTaggingMethod(Tag.IMPLICIT);
		userDefinedAnimations.setTagClass(Tag.CONTEXT);
		userDefinedAnimations.setTagNumber(56);
		super.addElement(predefinedSounds);
		predefinedSounds.setOptional(true);
		predefinedSounds.setTaggingMethod(Tag.IMPLICIT);
		predefinedSounds.setTagClass(Tag.CONTEXT);
		predefinedSounds.setTagNumber(57);
		super.addElement(userDefinedSounds);
		userDefinedSounds.setOptional(true);
		userDefinedSounds.setTaggingMethod(Tag.IMPLICIT);
		userDefinedSounds.setTagClass(Tag.CONTEXT);
		userDefinedSounds.setTagNumber(58);
		super.addElement(blackWhitePictures);
		blackWhitePictures.setOptional(true);
		blackWhitePictures.setTaggingMethod(Tag.IMPLICIT);
		blackWhitePictures.setTagClass(Tag.CONTEXT);
		blackWhitePictures.setTagNumber(59);
		super.addElement(standardWvg);
		standardWvg.setOptional(true);
		standardWvg.setTaggingMethod(Tag.IMPLICIT);
		standardWvg.setTagClass(Tag.CONTEXT);
		standardWvg.setTagNumber(60);
		super.addElement(characterSizeWvg);
		characterSizeWvg.setOptional(true);
		characterSizeWvg.setTaggingMethod(Tag.IMPLICIT);
		characterSizeWvg.setTagClass(Tag.CONTEXT);
		characterSizeWvg.setTagNumber(61);
		super.addElement(greyscalePictures);
		greyscalePictures.setOptional(true);
		greyscalePictures.setTaggingMethod(Tag.IMPLICIT);
		greyscalePictures.setTagClass(Tag.CONTEXT);
		greyscalePictures.setTagNumber(62);
		super.addElement(colourPictures);
		colourPictures.setOptional(true);
		colourPictures.setTaggingMethod(Tag.IMPLICIT);
		colourPictures.setTagClass(Tag.CONTEXT);
		colourPictures.setTagNumber(63);
		super.addElement(businessCards);
		businessCards.setOptional(true);
		businessCards.setTaggingMethod(Tag.IMPLICIT);
		businessCards.setTagClass(Tag.CONTEXT);
		businessCards.setTagNumber(64);
		super.addElement(calendarEntries);
		calendarEntries.setOptional(true);
		calendarEntries.setTaggingMethod(Tag.IMPLICIT);
		calendarEntries.setTagClass(Tag.CONTEXT);
		calendarEntries.setTagNumber(65);
		super.addElement(polyphonicMelodies);
		polyphonicMelodies.setOptional(true);
		polyphonicMelodies.setTaggingMethod(Tag.IMPLICIT);
		polyphonicMelodies.setTagClass(Tag.CONTEXT);
		polyphonicMelodies.setTagNumber(66);
		super.addElement(bit8PortNumberDest);
		bit8PortNumberDest.setOptional(true);
		bit8PortNumberDest.setTaggingMethod(Tag.IMPLICIT);
		bit8PortNumberDest.setTagClass(Tag.CONTEXT);
		bit8PortNumberDest.setTagNumber(67);
		super.addElement(bit16PortNumberDest);
		bit16PortNumberDest.setOptional(true);
		bit16PortNumberDest.setTaggingMethod(Tag.IMPLICIT);
		bit16PortNumberDest.setTagClass(Tag.CONTEXT);
		bit16PortNumberDest.setTagNumber(68);
		super.addElement(lmsgNrSeg);
		lmsgNrSeg.setOptional(true);
		lmsgNrSeg.setTaggingMethod(Tag.IMPLICIT);
		lmsgNrSeg.setTagClass(Tag.CONTEXT);
		lmsgNrSeg.setTagNumber(69);
		super.addElement(messageReference);
		messageReference.setOptional(true);
		messageReference.setTaggingMethod(Tag.IMPLICIT);
		messageReference.setTagClass(Tag.CONTEXT);
		messageReference.setTagNumber(70);
		super.addElement(boolSer);
		boolSer.setOptional(true);
		boolSer.setTaggingMethod(Tag.IMPLICIT);
		boolSer.setTagClass(Tag.CONTEXT);
		boolSer.setTagNumber(71);
		super.addElement(origLASN);
		origLASN.setOptional(true);
		origLASN.setTaggingMethod(Tag.IMPLICIT);
		origLASN.setTagClass(Tag.CONTEXT);
		origLASN.setTagNumber(72);
		super.addElement(recipLASN);
		recipLASN.setOptional(true);
		recipLASN.setTaggingMethod(Tag.IMPLICIT);
		recipLASN.setTagClass(Tag.CONTEXT);
		recipLASN.setTagNumber(73);
		super.addElement(origMsgID);
		origMsgID.setOptional(true);
		origMsgID.setTaggingMethod(Tag.IMPLICIT);
		origMsgID.setTagClass(Tag.CONTEXT);
		origMsgID.setTagNumber(74);
		super.addElement(recipMsgID);
		recipMsgID.setOptional(true);
		recipMsgID.setTaggingMethod(Tag.IMPLICIT);
		recipMsgID.setTagClass(Tag.CONTEXT);
		recipMsgID.setTagNumber(75);
		super.addElement(receiptDate);
		receiptDate.setOptional(true);
		receiptDate.setTaggingMethod(Tag.IMPLICIT);
		receiptDate.setTagClass(Tag.CONTEXT);
		receiptDate.setTagNumber(76);
		super.addElement(receiptTime);
		receiptTime.setOptional(true);
		receiptTime.setTaggingMethod(Tag.IMPLICIT);
		receiptTime.setTagClass(Tag.CONTEXT);
		receiptTime.setTagNumber(77);
		super.addElement(isr);
		isr.setOptional(true);
		isr.setTaggingMethod(Tag.IMPLICIT);
		isr.setTagClass(Tag.CONTEXT);
		isr.setTagNumber(78);
		super.addElement(recipAltAddress);
		recipAltAddress.setOptional(true);
		recipAltAddress.setTaggingMethod(Tag.IMPLICIT);
		recipAltAddress.setTagClass(Tag.CONTEXT);
		recipAltAddress.setTagNumber(79);
		super.addElement(generatedSegments);
		generatedSegments.setOptional(true);
		generatedSegments.setTaggingMethod(Tag.IMPLICIT);
		generatedSegments.setTagClass(Tag.CONTEXT);
		generatedSegments.setTagNumber(80);
		super.addElement(serviceType);
		serviceType.setOptional(true);
		serviceType.setTaggingMethod(Tag.IMPLICIT);
		serviceType.setTagClass(Tag.CONTEXT);
		serviceType.setTagNumber(81);
		super.addElement(deliveryAttempts);
		deliveryAttempts.setOptional(true);
		deliveryAttempts.setTaggingMethod(Tag.IMPLICIT);
		deliveryAttempts.setTagClass(Tag.CONTEXT);
		deliveryAttempts.setTagNumber(82);
		super.addElement(untranslOrigAddress);
		untranslOrigAddress.setOptional(true);
		untranslOrigAddress.setTaggingMethod(Tag.IMPLICIT);
		untranslOrigAddress.setTagClass(Tag.CONTEXT);
		untranslOrigAddress.setTagNumber(83);
		super.addElement(untranslOrigAddressGSM);
		untranslOrigAddressGSM.setOptional(true);
		untranslOrigAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		untranslOrigAddressGSM.setTagClass(Tag.CONTEXT);
		untranslOrigAddressGSM.setTagNumber(84);
		super.addElement(untranslRecipAddress);
		untranslRecipAddress.setOptional(true);
		untranslRecipAddress.setTaggingMethod(Tag.IMPLICIT);
		untranslRecipAddress.setTagClass(Tag.CONTEXT);
		untranslRecipAddress.setTagNumber(85);
		super.addElement(untranslRecipAddressGSM);
		untranslRecipAddressGSM.setOptional(true);
		untranslRecipAddressGSM.setTaggingMethod(Tag.IMPLICIT);
		untranslRecipAddressGSM.setTagClass(Tag.CONTEXT);
		untranslRecipAddressGSM.setTagNumber(86);
		super.addElement(msgError);
		msgError.setOptional(true);
		msgError.setTaggingMethod(Tag.IMPLICIT);
		msgError.setTagClass(Tag.CONTEXT);
		msgError.setTagNumber(87);
		super.addElement(tpDCS);
		tpDCS.setOptional(true);
		tpDCS.setTaggingMethod(Tag.IMPLICIT);
		tpDCS.setTagClass(Tag.CONTEXT);
		tpDCS.setTagNumber(88);
		super.addElement(subscriptionType);
		subscriptionType.setOptional(true);
		subscriptionType.setTaggingMethod(Tag.IMPLICIT);
		subscriptionType.setTagClass(Tag.CONTEXT);
		subscriptionType.setTagNumber(200);
		super.addElement(predefinedPaymentOption);
		predefinedPaymentOption.setOptional(true);
		predefinedPaymentOption.setTaggingMethod(Tag.IMPLICIT);
		predefinedPaymentOption.setTagClass(Tag.CONTEXT);
		predefinedPaymentOption.setTagNumber(201);
		super.addElement(iNRatedAmount);
		iNRatedAmount.setOptional(true);
		iNRatedAmount.setTaggingMethod(Tag.IMPLICIT);
		iNRatedAmount.setTagClass(Tag.CONTEXT);
		iNRatedAmount.setTagNumber(202);
	/* end of element setup */
	}


}
